default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: recipe_app_development

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
